# Generated by Django 3.0 on 2019-12-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='SecurityQuestions',
            new_name='SecurityQuestion',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='security_questions',
            new_name='security_question',
        ),
        migrations.AlterModelTable(
            name='securityquestion',
            table='security_question',
        ),
    ]
