# Generated by Django 3.0 on 2019-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191203_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='updateinDB', max_length=50, unique=True),
        ),
    ]
