# Generated by Django 3.0 on 2019-12-03 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191203_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=uuid.uuid1, max_length=50, null=True),
        ),
    ]
