# Generated by Django 3.0 on 2019-12-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191204_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup1',
            field=models.CharField(default='RDUUCJX7V8L9V4N', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='backup2',
            field=models.CharField(default='QCACZBYTTBL0Z9F', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='backup3',
            field=models.CharField(default='4ZLDH6H0SUB2NRZ', max_length=15),
        ),
    ]
