# Generated by Django 3.0 on 2019-12-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191204_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='backup1',
            field=models.CharField(default='HA4EEQOK33YRGXR', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup2',
            field=models.CharField(default='DRCYNIHOQ25E5P7', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup3',
            field=models.CharField(default='EBUO3FAL98WLK5S', max_length=15),
        ),
    ]
