# Generated by Django 3.0 on 2019-12-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191204_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup1',
            field=models.CharField(default='S3GF2VB5164CYBM', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup2',
            field=models.CharField(default='TOS0GZ79CVJIR5G', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup3',
            field=models.CharField(default='A5LRJ1AFJDRV3NJ', max_length=15),
        ),
    ]
