# Generated by Django 3.0 on 2019-12-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191204_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='backup1',
            field=models.CharField(default='7LE797SLBZCQMG5', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup2',
            field=models.CharField(default='DLSLIELY22SMIAV', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup3',
            field=models.CharField(default='KOW19V7L0GRGEBK', max_length=15),
        ),
    ]
