# Generated by Django 3.0 on 2019-12-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191205_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='backup1',
            field=models.CharField(default='3V771GT5E473WWB', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup2',
            field=models.CharField(default='FKVAVXC8YCSLT8X', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup3',
            field=models.CharField(default='UC4ZUNBG4OLWRMB', max_length=15),
        ),
    ]
