# Generated by Django 3.0 on 2019-12-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20191205_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='backup1',
            field=models.CharField(default='PX48RNCSA67N2LE', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup2',
            field=models.CharField(default='1FTKW8YLG7UFGZC', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup3',
            field=models.CharField(default='S9TLOF3IP4KNY51', max_length=15),
        ),
    ]
